# Generated by Django 2.1.4 on 2019-01-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('disponivel_em', models.ManyToManyField(to='schedule.Horario')),
                ('ensina', models.ManyToManyField(to='schedule.Modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='modalidade',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Sala'),
        ),
        migrations.AddField(
            model_name='aluna',
            name='disponivel_em',
            field=models.ManyToManyField(to='schedule.Horario'),
        ),
        migrations.AddField(
            model_name='aluna',
            name='pratica',
            field=models.ManyToManyField(to='schedule.Modalidade'),
        ),
    ]
